      	      .DATA              
SINWAVE       .WORD         02A0H		;85%PWM表格
              .WORD         02ACH
              .WORD         02B8H
              .WORD         02C4H
              .WORD         02D0H
              .WORD         02DCH
              .WORD         02E7H
              .WORD         02F3H
              .WORD         02FEH
              .WORD         0309H
              .WORD         0314H
              .WORD         031FH
              .WORD         032AH
              .WORD         0334H
              .WORD         033EH
              .WORD         0348H
              .WORD         0351H
              .WORD         035AH
              .WORD         0363H
              .WORD         036BH
              .WORD         0373H
              .WORD         037BH
              .WORD         0382H
              .WORD         0389H
              .WORD         0390H
              .WORD         0396H
              .WORD         039BH
              .WORD         03A0H
              .WORD         03A5H
              .WORD         03A9H
              .WORD         03ADH
              .WORD         03B0H
              .WORD         03B3H
              .WORD         03B5H
              .WORD         03B7H
              .WORD         03B8H
              .WORD         03B9H
              .WORD         03B9H
              .WORD         03B9H
              .WORD         03B8H
              .WORD         03B7H
              .WORD         03B5H
              .WORD         03B3H
              .WORD         03B0H
              .WORD         03ADH
              .WORD         03A9H
              .WORD         03A5H
              .WORD         03A0H
              .WORD         039BH
              .WORD         0396H
              .WORD         0390H
              .WORD         0389H
              .WORD         0382H
              .WORD         037BH
              .WORD         0373H
              .WORD         036BH
              .WORD         0363H
              .WORD         035AH
              .WORD         0351H
              .WORD         0348H
              .WORD         033EH
              .WORD         0334H
              .WORD         032AH
              .WORD         031FH
              .WORD         0314H
              .WORD         0309H
              .WORD         02FEH
              .WORD         02F3H
              .WORD         02E7H
              .WORD         02DCH
              .WORD         02D0H
              .WORD         02C4H
              .WORD         02B8H
              .WORD         02ACH
              .WORD         02A0H
              .WORD         0294H
              .WORD         0288H
              .WORD         027CH
              .WORD         0270H
              .WORD         0264H
              .WORD         0258H
              .WORD         024DH
              .WORD         0241H
              .WORD         0236H
              .WORD         022BH
              .WORD         0220H
              .WORD         0215H
              .WORD         020AH
              .WORD         0200H
              .WORD         01F6H
              .WORD         01ECH
              .WORD         01E3H
              .WORD         01DAH
              .WORD         01D1H
              .WORD         01C9H
              .WORD         01C1H
              .WORD         01B9H
              .WORD         01B2H
              .WORD         01ABH
              .WORD         01A4H
              .WORD         019EH
              .WORD         0199H
              .WORD         0194H
              .WORD         018FH
              .WORD         018BH
              .WORD         0187H
              .WORD         0184H
              .WORD         0181H
              .WORD         017FH
              .WORD         017DH
              .WORD         017CH
              .WORD         017BH
              .WORD         017BH
              .WORD         017BH
              .WORD         017CH
              .WORD         017DH
              .WORD         017FH
              .WORD         0181H
              .WORD         0184H
              .WORD         0187H
              .WORD         018BH
              .WORD         018FH
              .WORD         0194H
              .WORD         0199H
              .WORD         019EH
              .WORD         01A4H
              .WORD         01ABH
              .WORD         01B2H
              .WORD         01B9H
              .WORD         01C1H
              .WORD         01C9H
              .WORD         01D1H
              .WORD         01DAH
              .WORD         01E3H
              .WORD         01ECH
              .WORD         01F6H
              .WORD         0200H
              .WORD         020AH
              .WORD         0215H
              .WORD         0220H
              .WORD         022BH
              .WORD         0236H
              .WORD         0241H
              .WORD         024DH
              .WORD         0258H
              .WORD         0264H
              .WORD         0270H
              .WORD         027CH
              .WORD         0288H
              .WORD         0294H

SINWAVE1      .WORD         029CH		;25%脉宽表格
              .WORD         029FH
              .WORD         02A3H
              .WORD         02A6H
              .WORD         02AAH
              .WORD         02ADH
              .WORD         02B0H
              .WORD         02B4H
              .WORD         02B7H
              .WORD         02BAH
              .WORD         02BDH
              .WORD         02C1H
              .WORD         02C4H
              .WORD         02C7H
              .WORD         02CAH
              .WORD         02CCH
              .WORD         02CFH
              .WORD         02D2H
              .WORD         02D4H
              .WORD         02D7H
              .WORD         02D9H
              .WORD         02DBH
              .WORD         02DDH
              .WORD         02DFH
              .WORD         02E1H
              .WORD         02E3H
              .WORD         02E5H
              .WORD         02E6H
              .WORD         02E7H
              .WORD         02E9H
              .WORD         02EAH
              .WORD         02EBH
              .WORD         02ECH
              .WORD         02ECH
              .WORD         02EDH
              .WORD         02EDH
              .WORD         02EDH
              .WORD         02EDH
              .WORD         02EDH
              .WORD         02EDH
              .WORD         02EDH
              .WORD         02ECH
              .WORD         02ECH
              .WORD         02EBH
              .WORD         02EAH
              .WORD         02E9H
              .WORD         02E7H
              .WORD         02E6H
              .WORD         02E5H
              .WORD         02E3H
              .WORD         02E1H
              .WORD         02DFH
              .WORD         02DDH
              .WORD         02DBH
              .WORD         02D9H
              .WORD         02D7H
              .WORD         02D4H
              .WORD         02D2H
              .WORD         02CFH
              .WORD         02CCH
              .WORD         02CAH
              .WORD         02C7H
              .WORD         02C4H
              .WORD         02C1H
              .WORD         02BDH
              .WORD         02BAH
              .WORD         02B7H
              .WORD         02B4H
              .WORD         02B0H
              .WORD         02ADH
              .WORD         02AAH
              .WORD         02A6H
              .WORD         02A3H
              .WORD         029FH
              .WORD         029CH
              .WORD         0298H
              .WORD         0295H
              .WORD         0291H
              .WORD         028EH
              .WORD         028AH
              .WORD         0287H
              .WORD         0284H
              .WORD         0280H
              .WORD         027DH
              .WORD         027AH
              .WORD         0277H
              .WORD         0273H
              .WORD         0270H
              .WORD         026DH
              .WORD         026AH
              .WORD         0268H
              .WORD         0265H
              .WORD         0262H
              .WORD         0260H
              .WORD         025DH
              .WORD         025BH
              .WORD         0259H
              .WORD         0257H
              .WORD         0255H
              .WORD         0253H
              .WORD         0251H
              .WORD         024FH
              .WORD         024EH
              .WORD         024DH
              .WORD         024BH
              .WORD         024AH
              .WORD         0249H
              .WORD         0248H
              .WORD         0248H
              .WORD         0247H
              .WORD         0247H
              .WORD         0247H
              .WORD         0247H
              .WORD         0247H
              .WORD         0247H
              .WORD         0247H
              .WORD         0248H
              .WORD         0248H
              .WORD         0249H
              .WORD         024AH
              .WORD         024BH
              .WORD         024DH
              .WORD         024EH
              .WORD         024FH
              .WORD         0251H
              .WORD         0253H
              .WORD         0255H
              .WORD         0257H
              .WORD         0259H
              .WORD         025BH
              .WORD         025DH
              .WORD         0260H
              .WORD         0262H
              .WORD         0265H
              .WORD         0268H
              .WORD         026AH
              .WORD         026DH
              .WORD         0270H
              .WORD         0273H
              .WORD         0277H
              .WORD         027AH
              .WORD         027DH
              .WORD         0280H
              .WORD         0284H
              .WORD         0287H
              .WORD         028AH
              .WORD         028EH
              .WORD         0291H
              .WORD         0295H
              .WORD         0298H
              
              .DATA			;独立逆变表格(85%)
ACVDAT        .WORD         02A6H
              .WORD         02BFH
              .WORD         02D8H
              .WORD         02F1H
              .WORD         0309H
              .WORD         0321H
              .WORD         0339H
              .WORD         0351H
              .WORD         0369H
              .WORD         0380H
              .WORD         0396H
              .WORD         03ADH
              .WORD         03C2H
              .WORD         03D8H
              .WORD         03ECH
              .WORD         0400H
              .WORD         0414H
              .WORD         0427H
              .WORD         0439H
              .WORD         044AH
              .WORD         045BH
              .WORD         046AH
              .WORD         0479H
              .WORD         0488H
              .WORD         0495H
              .WORD         04A1H
              .WORD         04ADH
              .WORD         04B7H
              .WORD         04C1H
              .WORD         04CAH
              .WORD         04D1H
              .WORD         04D8H
              .WORD         04DEH
              .WORD         04E2H
              .WORD         04E6H
              .WORD         04E9H
              .WORD         04EAH
              .WORD         04EBH
              .WORD         04EAH
              .WORD         04E9H
              .WORD         04E6H
              .WORD         04E2H
              .WORD         04DEH
              .WORD         04D8H
              .WORD         04D1H
              .WORD         04CAH
              .WORD         04C1H
              .WORD         04B7H
              .WORD         04ADH
              .WORD         04A1H
              .WORD         0495H
              .WORD         0488H
              .WORD         0479H
              .WORD         046AH
              .WORD         045BH
              .WORD         044AH
              .WORD         0439H
              .WORD         0427H
              .WORD         0414H
              .WORD         0400H
              .WORD         03ECH
              .WORD         03D8H
              .WORD         03C2H
              .WORD         03ADH
              .WORD         0396H
              .WORD         0380H
              .WORD         0369H
              .WORD         0351H
              .WORD         0339H
              .WORD         0321H
              .WORD         0309H
              .WORD         02F1H
              .WORD         02D8H
              .WORD         02BFH
              .WORD         02A6H
              .WORD         028EH
              .WORD         0275H
              .WORD         025CH
              .WORD         0243H
              .WORD         022BH
              .WORD         0213H
              .WORD         01FBH
              .WORD         01E3H
              .WORD         01CBH
              .WORD         01B4H
              .WORD         019EH
              .WORD         0187H
              .WORD         0172H
              .WORD         015CH
              .WORD         0148H
              .WORD         0134H
              .WORD         0120H
              .WORD         010DH
              .WORD         0FBH
              .WORD         0EAH
              .WORD         0D9H
              .WORD         0CAH
              .WORD         0BBH
              .WORD         0ACH
              .WORD         09FH
              .WORD         093H
              .WORD         087H
              .WORD         07DH
              .WORD         073H
              .WORD         06AH
              .WORD         063H
              .WORD         05CH
              .WORD         056H
              .WORD         052H
              .WORD         04EH
              .WORD         04BH
              .WORD         04AH
              .WORD         049H
              .WORD         04AH
              .WORD         04BH
              .WORD         04EH
              .WORD         052H
              .WORD         056H
              .WORD         05CH
              .WORD         063H
              .WORD         06AH
              .WORD         073H
              .WORD         07DH
              .WORD         087H
              .WORD         093H
              .WORD         09FH
              .WORD         0ACH
              .WORD         0BBH
              .WORD         0CAH
              .WORD         0D9H
              .WORD         0EAH
              .WORD         0FBH
              .WORD         010DH
              .WORD         0120H
              .WORD         0134H
              .WORD         0148H
              .WORD         015CH
              .WORD         0172H
              .WORD         0187H
              .WORD         019EH
              .WORD         01B4H
              .WORD         01CBH
              .WORD         01E3H
              .WORD         01FBH
              .WORD         0213H
              .WORD         022BH
              .WORD         0243H
              .WORD         025CH
              .WORD         0275H
              .WORD         028EH
